[apidoc]
enabled = true
type = "swagger"
path = "/docs"

[database.postgresql]
url = "$DATABASE_URL"

[auth.jwt]
secret = "$JWT_SECRET"
expiration = 3600

[auth.basic]
username = "admin"
password = "123456"

[sso.google]
client_id = "123"
client_secret = "abc"
redirect_url = "http://localhost:8080/callback"
scopes = ["email"]

[ai.anthropic]
api_key = "$CLAUDE_API_KEY"
model = "claude-3-5-sonnet-latest"
